# rule identifiers turned on by default to exclude from running
disabled_rules:
  - identifier_name
  - type_name
  - line_length
  - file_length
  - multiple_closures_with_trailing_closure
  - nesting
  - switch_case_alignment
