name: Interactive Player Build and Distribution

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  Build-And-Deploy-iOS-App-To-Appstore:
    runs-on: macos-12
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.126.0
        with:
          ruby-version: 3.1.2

      - name: Build App and Upload to Appstore
        env:
          TEMP_KEYCHAIN_NAME: ${{ secrets.IOS_TEMP_KEYCHAIN_NAME_APPSTORE }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.IOS_TEMP_KEYCHAIN_PASSWORD_APPSTORE }}
          CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64_APPSTORE }}
          P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD_APPSTORE }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.INTERACTIVE_PROVISIONING_PROFILE_BASE64_APPSTORE }}
          EXPORT_OPTIONS_PLIST_BASE64: ${{ secrets.INTERACTIVE_PLAYER_EXPORT_OPTIONS_PLIST_BASE64_APPSTORE }}
          APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
          APPSTORE_CONNECT_KEY_CONTENT: ${{ secrets.APPSTORE_CONNECT_KEY_CONTENT }}
        run: |
          gem install bundler
          bundle install
          bundle exec fastlane build_and_deploy_to_appstore --env interactive-player-ios-appstore build_number:$GITHUB_RUN_NUMBER
