name: Tests

on:
  push:
    branches:
      - feature/upgrade-to-xcode-14.3

jobs:
  Run-UnitTests:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.126.0
        with:
          ruby-version: 3.1.2

      - name: Run Unit tests
        run: |
          gem install bundler
          bundle install
          bundle exec fastlane run_all_unit_tests --env tvos-tests
